swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/monthTransactions:
    post:
      security:
        - Bearer: []
      tags:
        - Month Transactions  
      summary: Find transactions of the provided month
      description: Return all transactions created in the provided month.
      operationId: findTransactionsByMonth
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Month Transactions List Payload
          required: true
          schema:
            $ref: '#/definitions/MonthTransactions'
      produces:
        - application/json
      responses:
        '200':
          description: Current transactions retrieved successfully
          schema:
            $ref: '#/definitions/MonthTransactionsResponse'
        '400':
          description: Invalid ID or month
        '500':
          description: Internal Server Error
  /user/profile/detailsTransaction:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Find the provided transaction
      description: Return information of the selected transaction.
      operationId: findTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Selected Transaction Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionID'
      produces:
        - application/json
      responses:
        '200':
          description: Selected transaction retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid ID
        '500':
          description: Internal Server Error        
  /user/profile/addInfoTransaction:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Add a new information in the transaction
      description: Create a new information with provided transaction
      operationId: createInformation
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Transaction Information Payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Information created successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid ID
        '500':
          description: Internal Server Error
  /user/profile/updateInfoTransaction:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Update information
      description: Update an information with provided transaction
      operationId: updateInformation
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Transaction Information Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionToUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Information updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid ID
        '500':
          description: Internal Server Error
  /user/profile/deleteInfoTransaction:
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Delete information
      description: Delete an information transaction with provided transaction
      operationId: deleteInformation
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Selected Transaction Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionID'
      produces:
        - application/json
      responses:
        '200':
          description: Information deleted successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid ID
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  TransactionID:
    properties:
      id:
        type: number
        description: Transaction ID
  MonthTransactions:
    properties:
      id:
        type: number
        description: Account ID
      month:
        type: string
        example: 2022-11
        description: Selected month (date String))
  MonthTransactionsResponse:
    type: object
    properties:
      status:
        type: integer
        example: 200
        description: Query status
      message:
        type: string
        example: OK | Successfully
        description: Query message
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  Transaction:
    type: object
    properties:
        id:
          type: number
          description: Transaction ID
        accountId:
          type: number
          description: Account ID
        description:
          type: string
          example: Fly Paris -> Alger
          description: Transaction description
        amount:
          type: number
          format: int64
          example: 35.99
          description: Transaction amount
        currency:
          type: string
          example: $
          description: Transaction currency
        type:
          type: string
          example: Shopping
          description: Transaction type
        category:
          type: string
          example: Travel
          description: Transaction category
        note:
          type: string
          example: Diner
          description: Transaction note
        createdAt:
          type: string
          example: 2023-12-13T12:00:00Z
          description: creation date
        updatedAt:
          type: string
          example: 2023-12-13T12:00:00Z
          description: last update date
  TransactionToUpdate:
    type: object
    properties:
        id:
          type: number
          description: Transaction ID
        accountId:
          type: number
          description: Account ID
        category:
          type: string
          example: Travel
          description: Transaction category
        note:
          type: string
          example: Diner
          description: Transaction note
        updatedAt:
          type: string
          example: 2023-12-13T12:00:00Z
          description: last update date        
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string

